- project:
    vars:
      functest_project_name: "eu-de_zuul_go"
    check:
      jobs:
        - golangci-lint
        - golang-make-functional
    gate:
      jobs:
        - golangci-lint
        - golang-make-functional
