#- job:
#    name: crutch-house
#    description: |
#      Base job for executing functional tests with golang-go against OTC
#    parent: golang-go-test
#    pre-run: playbooks/acceptance-pre.yaml
#    post-run: playbooks/acceptance-post.yaml
#    timeout: 3000

- project:
    vars:
      go_command: "test"
      go_package_dir: "./..."
      go_install_dir: "/usr/local"
    check:
      jobs:
        - golangci-lint
        - golang-functional
        - golang-make:
            vars:
              make_command: test
    gate:
      jobs:
        - golangci-lint
        - golang-functional
