- project:
    vars:
      go_command: "test"
      go_package_dir: "./..."
      go_install_dir: "/usr/local"
    check:
      jobs:
        - golangci-lint
        - golang-make-functional
    gate:
      jobs:
        - golangci-lint
        - golang-make-functional
