---
- hosts: localhost
  tasks:
    # TODO:
    # - clean the resources, which might have been created
    # - revoke the temp token explicitely
    - name: read token
      delegate_to: localhost
      command: "cat {{ zuul.executor.work_root }}/.{{ zuul.build}}"
      register: token_data
      no_log: true

    - name: delete data file
      file:
        path: "{{ zuul.executor.work_root }}/.{{ zuul.build }}"
        state: absent

    - include_role:
        name: revoke_token
      vars:
        cloud: "{{ cloud_config }}"
        token: "{{ token_data.stdout }}"
